package system.model;

import java.io.Serializable;
import java.util.Date;

public class DeviceFunction implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column device_function.id
     *
     * @mbg.generated
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column device_function.device_code
     *
     * @mbg.generated
     */
    private String deviceCode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column device_function.real_num
     *
     * @mbg.generated
     */
    private Integer realNum;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column device_function.hstory_num
     *
     * @mbg.generated
     */
    private Integer hstoryNum;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column device_function.cur_num
     *
     * @mbg.generated
     */
    private Integer curNum;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column device_function.on_time
     *
     * @mbg.generated
     */
    private Date onTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column device_function.this_duration
     *
     * @mbg.generated
     */
    private Integer thisDuration;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column device_function.total_duration
     *
     * @mbg.generated
     */
    private Integer totalDuration;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column device_function.last_upload_time
     *
     * @mbg.generated
     */
    private Date lastUploadTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table device_function
     *
     * @mbg.generated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column device_function.id
     *
     * @return the value of device_function.id
     *
     * @mbg.generated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column device_function.id
     *
     * @param id the value for device_function.id
     *
     * @mbg.generated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column device_function.device_code
     *
     * @return the value of device_function.device_code
     *
     * @mbg.generated
     */
    public String getDeviceCode() {
        return deviceCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column device_function.device_code
     *
     * @param deviceCode the value for device_function.device_code
     *
     * @mbg.generated
     */
    public void setDeviceCode(String deviceCode) {
        this.deviceCode = deviceCode == null ? null : deviceCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column device_function.real_num
     *
     * @return the value of device_function.real_num
     *
     * @mbg.generated
     */
    public Integer getRealNum() {
        return realNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column device_function.real_num
     *
     * @param realNum the value for device_function.real_num
     *
     * @mbg.generated
     */
    public void setRealNum(Integer realNum) {
        this.realNum = realNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column device_function.hstory_num
     *
     * @return the value of device_function.hstory_num
     *
     * @mbg.generated
     */
    public Integer getHstoryNum() {
        return hstoryNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column device_function.hstory_num
     *
     * @param hstoryNum the value for device_function.hstory_num
     *
     * @mbg.generated
     */
    public void setHstoryNum(Integer hstoryNum) {
        this.hstoryNum = hstoryNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column device_function.cur_num
     *
     * @return the value of device_function.cur_num
     *
     * @mbg.generated
     */
    public Integer getCurNum() {
        return curNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column device_function.cur_num
     *
     * @param curNum the value for device_function.cur_num
     *
     * @mbg.generated
     */
    public void setCurNum(Integer curNum) {
        this.curNum = curNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column device_function.on_time
     *
     * @return the value of device_function.on_time
     *
     * @mbg.generated
     */
    public Date getOnTime() {
        return onTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column device_function.on_time
     *
     * @param onTime the value for device_function.on_time
     *
     * @mbg.generated
     */
    public void setOnTime(Date onTime) {
        this.onTime = onTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column device_function.this_duration
     *
     * @return the value of device_function.this_duration
     *
     * @mbg.generated
     */
    public Integer getThisDuration() {
        return thisDuration;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column device_function.this_duration
     *
     * @param thisDuration the value for device_function.this_duration
     *
     * @mbg.generated
     */
    public void setThisDuration(Integer thisDuration) {
        this.thisDuration = thisDuration;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column device_function.total_duration
     *
     * @return the value of device_function.total_duration
     *
     * @mbg.generated
     */
    public Integer getTotalDuration() {
        return totalDuration;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column device_function.total_duration
     *
     * @param totalDuration the value for device_function.total_duration
     *
     * @mbg.generated
     */
    public void setTotalDuration(Integer totalDuration) {
        this.totalDuration = totalDuration;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column device_function.last_upload_time
     *
     * @return the value of device_function.last_upload_time
     *
     * @mbg.generated
     */
    public Date getLastUploadTime() {
        return lastUploadTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column device_function.last_upload_time
     *
     * @param lastUploadTime the value for device_function.last_upload_time
     *
     * @mbg.generated
     */
    public void setLastUploadTime(Date lastUploadTime) {
        this.lastUploadTime = lastUploadTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table device_function
     *
     * @mbg.generated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", deviceCode=").append(deviceCode);
        sb.append(", realNum=").append(realNum);
        sb.append(", hstoryNum=").append(hstoryNum);
        sb.append(", curNum=").append(curNum);
        sb.append(", onTime=").append(onTime);
        sb.append(", thisDuration=").append(thisDuration);
        sb.append(", totalDuration=").append(totalDuration);
        sb.append(", lastUploadTime=").append(lastUploadTime);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}