package system.model;

import java.io.Serializable;
import java.util.Date;

public class DeviceImage implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column device_image.id
     *
     * @mbg.generated
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column device_image.device_code
     *
     * @mbg.generated
     */
    private String deviceCode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column device_image.device_image_path
     *
     * @mbg.generated
     */
    private String deviceImagePath;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column device_image.image_upload_time
     *
     * @mbg.generated
     */
    private Date imageUploadTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column device_image.image_type
     *
     * @mbg.generated
     */
    private Integer imageType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table device_image
     *
     * @mbg.generated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column device_image.id
     *
     * @return the value of device_image.id
     *
     * @mbg.generated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column device_image.id
     *
     * @param id the value for device_image.id
     *
     * @mbg.generated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column device_image.device_code
     *
     * @return the value of device_image.device_code
     *
     * @mbg.generated
     */
    public String getDeviceCode() {
        return deviceCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column device_image.device_code
     *
     * @param deviceCode the value for device_image.device_code
     *
     * @mbg.generated
     */
    public void setDeviceCode(String deviceCode) {
        this.deviceCode = deviceCode == null ? null : deviceCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column device_image.device_image_path
     *
     * @return the value of device_image.device_image_path
     *
     * @mbg.generated
     */
    public String getDeviceImagePath() {
        return deviceImagePath;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column device_image.device_image_path
     *
     * @param deviceImagePath the value for device_image.device_image_path
     *
     * @mbg.generated
     */
    public void setDeviceImagePath(String deviceImagePath) {
        this.deviceImagePath = deviceImagePath == null ? null : deviceImagePath.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column device_image.image_upload_time
     *
     * @return the value of device_image.image_upload_time
     *
     * @mbg.generated
     */
    public Date getImageUploadTime() {
        return imageUploadTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column device_image.image_upload_time
     *
     * @param imageUploadTime the value for device_image.image_upload_time
     *
     * @mbg.generated
     */
    public void setImageUploadTime(Date imageUploadTime) {
        this.imageUploadTime = imageUploadTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column device_image.image_type
     *
     * @return the value of device_image.image_type
     *
     * @mbg.generated
     */
    public Integer getImageType() {
        return imageType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column device_image.image_type
     *
     * @param imageType the value for device_image.image_type
     *
     * @mbg.generated
     */
    public void setImageType(Integer imageType) {
        this.imageType = imageType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table device_image
     *
     * @mbg.generated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", deviceCode=").append(deviceCode);
        sb.append(", deviceImagePath=").append(deviceImagePath);
        sb.append(", imageUploadTime=").append(imageUploadTime);
        sb.append(", imageType=").append(imageType);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}