package system.dao;

import org.apache.ibatis.annotations.Param;
import system.model.Area;

import java.util.List;

public interface AreaMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table area
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table area
     *
     * @mbg.generated
     */
    int insert(Area record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table area
     *
     * @mbg.generated
     */
    int insertSelective(Area record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table area
     *
     * @mbg.generated
     */
    Area selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table area
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(Area record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table area
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(Area record);

    Area findByAreaName(@Param("areaName")String areaName);

    /**
     * 查询全部子地区
     */
    List<Integer> findSonArea(@Param("areaId") Integer areaId);

    /**
     * 查询子地区（一级）
     */
    List<Area> findByParentId(@Param("areaId")Integer areaId);

    /**
     * 根据地区id查询地区
     */
    Area findByAreaId(@Param("areaId")Integer areaId);
}