package system.dao;

import org.apache.ibatis.annotations.Param;
import system.model.DeviceImage;

import java.util.List;

public interface DeviceImageMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table device_image
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table device_image
     *
     * @mbg.generated
     */
    int insert(DeviceImage record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table device_image
     *
     * @mbg.generated
     */
    int insertSelective(DeviceImage record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table device_image
     *
     * @mbg.generated
     */
    DeviceImage selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table device_image
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(DeviceImage record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table device_image
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(DeviceImage record);

    /**
     * 根据设备码和图片类型获取图片
     */
    List<DeviceImage> findBydeviceCode(@Param("deviceCode") Integer deviceCode, @Param("imageType") Integer imageType);


}