package system.dao;

import system.model.DeviceFunction;

public interface DeviceFunctionMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table device_function
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table device_function
     *
     * @mbg.generated
     */
    int insert(DeviceFunction record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table device_function
     *
     * @mbg.generated
     */
    int insertSelective(DeviceFunction record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table device_function
     *
     * @mbg.generated
     */
    DeviceFunction selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table device_function
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(DeviceFunction record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table device_function
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(DeviceFunction record);
}